#!/bin/bash

if [ "$1" = "make" ]
then
    echo "make project"
    mvn clean package
elif [ "$1" = "deploy" ]
then
    echo "deploy project components"
    mvn -DdeployOnly=true deploy
else
    java -D -jar /home/sevenbits/Projects/ads/target/ads-0.3.0-SNAPSHOT-jar-with-dependencies.jar $@
fi
