#!/bin/bash
if [ "$1" = "make" ]
then
    if [ "$2" = "jar" ]
    then
        if [ "$3" = "sources" ]
        then
            echo "make project jars (source)"
            echo "execute [mvn clean install -Dbuild.format=jar -Dbuild.unpack=true -Dbuild.includeBaseDirectory=false -Dbuild.exclude=]"
            mvn clean install -Dbuild.format=jar -Dbuild.unpack=true -Dbuild.includeBaseDirectory=false -Dbuild.exclude=
        else
            echo "make project jars"
            echo "execute [mvn clean install -Dbuild.format=jar -Dbuild.unpack=true -Dbuild.includeBaseDirectory=false -Dbuild.exclude=**/**]"
            mvn clean install -Dbuild.format=jar -Dbuild.unpack=true -Dbuild.includeBaseDirectory=false -Dbuild.exclude=**/**
        fi
    elif [ "$2" = "zip" ]
    then
        echo "make project zips"
        echo "execute [mvn clean install -Dbuild.format=zip -Dbuild.unpack=false -Dbuild.includeBaseDirectory=true -Dbuild.exclude=**/**]"
        mvn clean install -Dbuild.format=zip -Dbuild.unpack=false -Dbuild.includeBaseDirectory=true -Dbuild.exclude=**/**
    else
        echo "make project jars"
        echo "execute [mvn clean install -Dbuild.format=jar -Dbuild.unpack=true -Dbuild.includeBaseDirectory=true -Dbuild.exclude=**/**]"
        mvn clean install -Dbuild.format=jar -Dbuild.unpack=true -Dbuild.includeBaseDirectory=false -Dbuild.exclude=**/**
    fi
elif [ "$1" = "deploy" ]
then
    if [ "$2" = "jar" ]
    then
        if [ "$3" = "sources" ]
        then
            echo "deploy jar artifacts (source)"
            echo "execute [mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=jar -Ddeploy.classifier=sources]"
            mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=jar -Ddeploy.classifier=sources
        else
            echo "deploy jar artifacts"
            echo "execute [mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=jar -Ddeploy.classifier=]"
            mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=jar -Ddeploy.classifier=
        fi
    elif [ "$2" = "zip" ]
    then
        echo "deploy zip artifacts"
        echo "execute [mvn -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=zip -Ddeploy.classifier=]"
        mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=zip -Ddeploy.classifier=
    else
        echo "deploy jar artifacts"
        echo "execute [mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=jar -Ddeploy.classifier=]"
        mvn deploy -Dmaven.test.skip=true -DdeployOnly=true -Ddeploy.format=jar -Ddeploy.classifier=
    fi
    echo "deploy project components"
else
    echo "das ..."
    java -D -jar /usr/share/das/das.jar $@
fi