/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package info.smart_tools.smartactors.actors.validate_form_data.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int COMPULSORY = 6;
  /** RegularExpression Id. */
  int RUSSIAN = 7;
  /** RegularExpression Id. */
  int ADDRESS = 8;
  /** RegularExpression Id. */
  int HOUSE = 9;
  /** RegularExpression Id. */
  int EMAIL = 10;
  /** RegularExpression Id. */
  int PASSWORD = 11;
  /** RegularExpression Id. */
  int NUMERIC = 12;
  /** RegularExpression Id. */
  int BARCODE = 13;
  /** RegularExpression Id. */
  int ARTICUL = 14;
  /** RegularExpression Id. */
  int PHONE = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"&&\"",
    "\"\\u043e\\u0431\\u044f\\u0437\\u0430\\u0442\\u0435\\u043b\\u044c\\u043d\\u043e\\u0435\"",
    "\"\\u0440\\u0443\\u0441\\u0441\\u043a\\u0438\\u0439\"",
    "\"\\u0430\\u0434\\u0440\\u0435\\u0441\"",
    "\"\\u0434\\u043e\\u043c\"",
    "\"email\"",
    "\"password\"",
    "\"\\u0438\\u0437 \\u0446\\u0438\\u0444\\u0440\"",
    "\"\\u0448\\u0442\\u0440\\u0438\\u0445\\u043a\\u043e\\u0434\"",
    "\"\\u0430\\u0440\\u0442\\u0438\\u043a\\u0443\\u043b\"",
    "\"\\u0442\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d\"",
    "\"\\u0447\\u0438\\u0441\\u043b\\u043e\"",
  };

}
